export type CalculatorCategory =
  | "fire"
  | "retirement"
  | "investing"
  | "real-estate"
  | "loans"
  | "savings"
  | "taxes"
  | "business"
  | "personal-finance"
  | "currency"
  | "insurance";

export interface CalculatorMeta {
  id: string;
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  category: CalculatorCategory;
  icon: string;
  color: string;
  tags: string[];
  related: string[];
  popular?: boolean;
  featured?: boolean;
  timeToComplete?: string;
  seoTitle: string;
  seoDescription: string;
  keywords: string[];
}

export const CATEGORY_META: Record<CalculatorCategory, { name: string; description: string; icon: string; color: string }> = {
  fire: { name: "FIRE & Financial Independence", description: "Calculators for early retirement planning", icon: "🔥", color: "from-orange-500 to-red-500" },
  retirement: { name: "Retirement Planning", description: "Plan your retirement with precision", icon: "🏖️", color: "from-blue-500 to-cyan-500" },
  investing: { name: "Investing", description: "Grow your wealth with smart investing", icon: "📈", color: "from-green-500 to-emerald-500" },
  "real-estate": { name: "Real Estate", description: "Evaluate property investments", icon: "🏠", color: "from-purple-500 to-violet-500" },
  loans: { name: "Loans & Debt", description: "Manage and pay off debt faster", icon: "💳", color: "from-rose-500 to-pink-500" },
  savings: { name: "Savings", description: "Build your savings and emergency fund", icon: "🏦", color: "from-teal-500 to-cyan-500" },
  taxes: { name: "Taxes", description: "Estimate and optimize your taxes", icon: "📊", color: "from-yellow-500 to-amber-500" },
  business: { name: "Business Finance", description: "Financial analysis for businesses", icon: "💼", color: "from-indigo-500 to-blue-500" },
  "personal-finance": { name: "Personal Finance", description: "Take control of your finances", icon: "💰", color: "from-slate-500 to-gray-500" },
  currency: { name: "Currency & Banking", description: "Currency and interest rate tools", icon: "💱", color: "from-sky-500 to-blue-500" },
  insurance: { name: "Insurance", description: "Calculate your insurance needs", icon: "🛡️", color: "from-emerald-500 to-green-500" },
};

export const CALCULATORS: CalculatorMeta[] = [
  // FIRE
  {
    id: "fire", slug: "fire-calculator", name: "FIRE Calculator", shortDescription: "Find your financial independence number",
    description: "Calculate exactly how much you need to retire early with the FIRE method. Get your FI number, timeline, and personalized roadmap.",
    category: "fire", icon: "🔥", color: "from-orange-500 to-red-500", popular: true, featured: true, timeToComplete: "3 min",
    tags: ["fire", "early retirement", "financial independence", "FI number"],
    related: ["coast-fire-calculator", "lean-fire-calculator", "fat-fire-calculator", "retirement-calculator", "safe-withdrawal-rate-calculator"],
    seoTitle: "FIRE Calculator – Financial Independence Retire Early Number",
    seoDescription: "Calculate your FIRE number, timeline to financial independence, and retirement corpus needed using the 4% safe withdrawal rate rule.",
    keywords: ["FIRE calculator", "financial independence calculator", "early retirement calculator", "FI number calculator"],
  },
  {
    id: "coast-fire", slug: "coast-fire-calculator", name: "Coast FIRE Calculator", shortDescription: "Find when you can stop saving and coast to retirement",
    description: "Calculate your Coast FIRE number — the amount you need invested today to retire at a traditional age without saving another dollar.",
    category: "fire", icon: "🌊", color: "from-blue-500 to-cyan-500", timeToComplete: "3 min",
    tags: ["coast fire", "financial independence", "compound interest"],
    related: ["fire-calculator", "lean-fire-calculator", "compound-interest-calculator", "investment-return-calculator"],
    seoTitle: "Coast FIRE Calculator – When Can You Stop Saving?",
    seoDescription: "Calculate your Coast FIRE number and find out when you can stop saving for retirement and let compound interest do the work.",
    keywords: ["coast FIRE calculator", "coast fire number", "coasting to retirement"],
  },
  {
    id: "lean-fire", slug: "lean-fire-calculator", name: "Lean FIRE Calculator", shortDescription: "Retire early on a lean budget",
    description: "Plan for Lean FIRE with a frugal lifestyle. Calculate your minimal retirement corpus and timeline for ultra-early retirement.",
    category: "fire", icon: "🌱", color: "from-green-500 to-teal-500", timeToComplete: "3 min",
    tags: ["lean fire", "frugal retirement", "minimalist FIRE"],
    related: ["fire-calculator", "fat-fire-calculator", "barista-fire-calculator", "budget-planner"],
    seoTitle: "Lean FIRE Calculator – Retire Early on a Frugal Budget",
    seoDescription: "Calculate your Lean FIRE number for minimalist early retirement. Find the minimum corpus needed for financial independence.",
    keywords: ["lean FIRE calculator", "frugal retirement", "lean fire number"],
  },
  {
    id: "fat-fire", slug: "fat-fire-calculator", name: "Fat FIRE Calculator", shortDescription: "Retire early with a luxurious lifestyle",
    description: "Calculate your Fat FIRE number for a wealthy early retirement. Plan for $100k+ annual spending in retirement.",
    category: "fire", icon: "💎", color: "from-purple-500 to-pink-500", timeToComplete: "3 min",
    tags: ["fat fire", "luxury retirement", "wealthy retirement"],
    related: ["fire-calculator", "lean-fire-calculator", "retirement-calculator", "portfolio-allocation-calculator"],
    seoTitle: "Fat FIRE Calculator – Retire Early with Luxury Spending",
    seoDescription: "Calculate your Fat FIRE number for a luxurious early retirement with $100k+ annual expenses. Plan your wealthy retirement today.",
    keywords: ["fat FIRE calculator", "fat fire number", "luxury early retirement"],
  },
  {
    id: "barista-fire", slug: "barista-fire-calculator", name: "Barista FIRE Calculator", shortDescription: "Semi-retire with part-time work income",
    description: "Calculate your Barista FIRE number — combining investment income with part-time work for an early semi-retirement.",
    category: "fire", icon: "☕", color: "from-amber-500 to-orange-500", timeToComplete: "3 min",
    tags: ["barista fire", "semi-retirement", "part-time retirement"],
    related: ["fire-calculator", "coast-fire-calculator", "retirement-income-calculator"],
    seoTitle: "Barista FIRE Calculator – Semi-Retirement Planning",
    seoDescription: "Calculate your Barista FIRE number combining part-time income with investments for semi-retirement planning.",
    keywords: ["barista FIRE calculator", "semi-retirement calculator", "part-time fire"],
  },
  {
    id: "financial-independence", slug: "financial-independence-calculator", name: "Financial Independence Calculator", shortDescription: "Calculate your path to FI",
    description: "Comprehensive financial independence calculator covering savings rate, FI number, and timeline to freedom.",
    category: "fire", icon: "🏆", color: "from-yellow-500 to-orange-500", popular: true, timeToComplete: "5 min",
    tags: ["financial independence", "FI", "savings rate"],
    related: ["fire-calculator", "savings-goal-calculator", "net-worth-calculator"],
    seoTitle: "Financial Independence Calculator – Your Path to Freedom",
    seoDescription: "Calculate your financial independence number, savings rate needed, and exact timeline to FI with this comprehensive calculator.",
    keywords: ["financial independence calculator", "FI calculator", "financial freedom calculator"],
  },
  {
    id: "retirement-age", slug: "retirement-age-calculator", name: "Retirement Age Calculator", shortDescription: "Find your ideal retirement age",
    description: "Calculate the earliest age you can retire based on your savings, expenses, and investment returns.",
    category: "fire", icon: "🎯", color: "from-indigo-500 to-blue-500", timeToComplete: "3 min",
    tags: ["retirement age", "early retirement", "when to retire"],
    related: ["fire-calculator", "retirement-calculator", "safe-withdrawal-rate-calculator"],
    seoTitle: "Retirement Age Calculator – When Can You Retire?",
    seoDescription: "Calculate your earliest possible retirement age based on current savings, monthly contributions, and expected returns.",
    keywords: ["retirement age calculator", "when can I retire", "earliest retirement age"],
  },
  {
    id: "fire-progress", slug: "fire-progress-tracker", name: "FIRE Progress Tracker", shortDescription: "Track your journey to financial independence",
    description: "Monitor your progress toward FIRE with milestone tracking, net worth trends, and savings rate analysis.",
    category: "fire", icon: "📍", color: "from-rose-500 to-red-500", timeToComplete: "5 min",
    tags: ["fire progress", "net worth tracker", "FI milestone"],
    related: ["fire-calculator", "net-worth-calculator", "financial-independence-calculator"],
    seoTitle: "FIRE Progress Tracker – Monitor Your FI Journey",
    seoDescription: "Track your progress toward financial independence with milestone tracking, net worth trends, and savings rate analysis.",
    keywords: ["FIRE progress tracker", "financial independence tracker", "FI progress calculator"],
  },

  // RETIREMENT
  {
    id: "retirement", slug: "retirement-calculator", name: "Retirement Calculator", shortDescription: "Plan your retirement savings with precision",
    description: "Comprehensive retirement planning calculator with Social Security, pension, inflation adjustments, and Monte Carlo projections.",
    category: "retirement", icon: "🏖️", color: "from-blue-500 to-cyan-500", popular: true, featured: true, timeToComplete: "5 min",
    tags: ["retirement planning", "401k", "IRA", "pension"],
    related: ["401k-calculator", "roth-ira-calculator", "social-security-calculator", "fire-calculator"],
    seoTitle: "Retirement Calculator – Free Retirement Planning Tool 2024",
    seoDescription: "Calculate how much you need to retire comfortably. Includes Social Security, pension, inflation, and 30-year projections.",
    keywords: ["retirement calculator", "retirement planning calculator", "how much to retire"],
  },
  {
    id: "401k", slug: "401k-calculator", name: "401(k) Calculator", shortDescription: "Maximize your 401(k) retirement savings",
    description: "Calculate your 401(k) balance at retirement, employer match impact, and optimal contribution strategy.",
    category: "retirement", icon: "🏛️", color: "from-slate-500 to-blue-500", popular: true, timeToComplete: "3 min",
    tags: ["401k", "employer match", "retirement savings", "pre-tax"],
    related: ["roth-ira-calculator", "traditional-ira-calculator", "retirement-calculator"],
    seoTitle: "401(k) Calculator – Maximize Your Retirement Savings",
    seoDescription: "Calculate your 401(k) balance at retirement including employer match, tax savings, and contribution limits.",
    keywords: ["401k calculator", "401(k) calculator", "retirement savings calculator"],
  },
  {
    id: "roth-ira", slug: "roth-ira-calculator", name: "Roth IRA Calculator", shortDescription: "Tax-free retirement growth projections",
    description: "Calculate your Roth IRA growth with tax-free compounding, contribution limits, and retirement income projections.",
    category: "retirement", icon: "⭐", color: "from-yellow-500 to-orange-500", popular: true, timeToComplete: "3 min",
    tags: ["roth IRA", "tax-free retirement", "IRA contribution"],
    related: ["401k-calculator", "traditional-ira-calculator", "retirement-calculator"],
    seoTitle: "Roth IRA Calculator – Tax-Free Retirement Growth",
    seoDescription: "Calculate your Roth IRA balance at retirement with tax-free compound growth and contribution limit tracking.",
    keywords: ["roth IRA calculator", "roth IRA growth calculator", "roth IRA retirement"],
  },
  {
    id: "traditional-ira", slug: "traditional-ira-calculator", name: "Traditional IRA Calculator", shortDescription: "Tax-deferred retirement savings",
    description: "Calculate traditional IRA growth with tax-deferred compounding, deduction eligibility, and required minimum distributions.",
    category: "retirement", icon: "🏦", color: "from-green-500 to-teal-500", timeToComplete: "3 min",
    tags: ["traditional IRA", "tax-deferred", "IRA deduction"],
    related: ["roth-ira-calculator", "401k-calculator", "rmd-calculator"],
    seoTitle: "Traditional IRA Calculator – Tax-Deferred Retirement Savings",
    seoDescription: "Calculate your Traditional IRA growth, tax deductions, and required minimum distributions at retirement.",
    keywords: ["traditional IRA calculator", "IRA calculator", "tax-deferred retirement"],
  },
  {
    id: "pension", slug: "pension-calculator", name: "Pension Calculator", shortDescription: "Calculate your defined benefit pension",
    description: "Estimate your monthly pension benefit based on years of service, salary, and plan formula.",
    category: "retirement", icon: "🎖️", color: "from-indigo-500 to-purple-500", timeToComplete: "3 min",
    tags: ["pension", "defined benefit", "retirement benefit"],
    related: ["retirement-calculator", "social-security-calculator", "retirement-income-calculator"],
    seoTitle: "Pension Calculator – Estimate Your Monthly Pension Benefit",
    seoDescription: "Calculate your monthly pension benefit based on years of service, final salary, and pension formula.",
    keywords: ["pension calculator", "pension benefit calculator", "defined benefit calculator"],
  },
  {
    id: "social-security", slug: "social-security-calculator", name: "Social Security Benefits Calculator", shortDescription: "Estimate your Social Security income",
    description: "Estimate your monthly Social Security benefit at different claiming ages and optimize your claiming strategy.",
    category: "retirement", icon: "🇺🇸", color: "from-blue-600 to-blue-400", timeToComplete: "3 min",
    tags: ["social security", "SSA benefits", "retirement income"],
    related: ["retirement-calculator", "pension-calculator", "retirement-income-calculator"],
    seoTitle: "Social Security Benefits Calculator – Estimate Your Monthly Check",
    seoDescription: "Estimate your Social Security retirement benefits and find the optimal age to claim for maximum lifetime income.",
    keywords: ["social security calculator", "social security benefits calculator", "SSA calculator"],
  },
  {
    id: "safe-withdrawal-rate", slug: "safe-withdrawal-rate-calculator", name: "Safe Withdrawal Rate Calculator", shortDescription: "Find your safe annual retirement drawdown",
    description: "Calculate how much you can safely withdraw from your retirement portfolio each year without running out of money.",
    category: "retirement", icon: "🎚️", color: "from-teal-500 to-green-500", timeToComplete: "3 min",
    tags: ["safe withdrawal rate", "4% rule", "retirement drawdown"],
    related: ["fire-calculator", "retirement-calculator", "retirement-income-calculator"],
    seoTitle: "Safe Withdrawal Rate Calculator – The 4% Rule & Beyond",
    seoDescription: "Calculate your safe withdrawal rate based on portfolio size, time horizon, and asset allocation. Go beyond the 4% rule.",
    keywords: ["safe withdrawal rate calculator", "4% rule calculator", "retirement withdrawal calculator"],
  },
  {
    id: "rmd", slug: "rmd-calculator", name: "Required Minimum Distribution (RMD) Calculator", shortDescription: "Calculate your annual IRA withdrawals",
    description: "Calculate your Required Minimum Distribution from traditional IRA and 401(k) accounts to avoid IRS penalties.",
    category: "retirement", icon: "📋", color: "from-red-500 to-orange-500", timeToComplete: "2 min",
    tags: ["RMD", "required minimum distribution", "IRA withdrawal"],
    related: ["traditional-ira-calculator", "401k-calculator", "retirement-income-calculator"],
    seoTitle: "RMD Calculator – Required Minimum Distribution Calculator",
    seoDescription: "Calculate your Required Minimum Distribution (RMD) from IRA and 401(k) accounts to stay IRS-compliant.",
    keywords: ["RMD calculator", "required minimum distribution calculator", "IRA RMD"],
  },
  {
    id: "retirement-income", slug: "retirement-income-calculator", name: "Retirement Income Calculator", shortDescription: "Plan all your retirement income sources",
    description: "Calculate total retirement income from all sources: Social Security, pension, 401(k), IRA, and investments.",
    category: "retirement", icon: "💵", color: "from-emerald-500 to-green-500", timeToComplete: "5 min",
    tags: ["retirement income", "income planning", "retirement cash flow"],
    related: ["retirement-calculator", "social-security-calculator", "safe-withdrawal-rate-calculator"],
    seoTitle: "Retirement Income Calculator – Total Income from All Sources",
    seoDescription: "Calculate your total retirement income from Social Security, pension, investments, and other sources.",
    keywords: ["retirement income calculator", "retirement cash flow calculator", "income in retirement"],
  },
  {
    id: "retirement-savings-gap", slug: "retirement-savings-gap-calculator", name: "Retirement Savings Gap Calculator", shortDescription: "Find out if you're saving enough",
    description: "Calculate the gap between your projected retirement savings and what you'll actually need, with a plan to close it.",
    category: "retirement", icon: "📉", color: "from-rose-500 to-red-500", timeToComplete: "4 min",
    tags: ["retirement gap", "savings shortfall", "retirement planning"],
    related: ["retirement-calculator", "401k-calculator", "savings-goal-calculator"],
    seoTitle: "Retirement Savings Gap Calculator – Are You Saving Enough?",
    seoDescription: "Calculate your retirement savings gap and find out exactly how much more you need to save to retire comfortably.",
    keywords: ["retirement savings gap calculator", "retirement shortfall calculator", "am I saving enough"],
  },

  // INVESTING
  {
    id: "sip", slug: "sip-calculator", name: "SIP Calculator", shortDescription: "Calculate returns on systematic investment plans",
    description: "Calculate the future value of your SIP investments with compounding. Perfect for mutual fund SIP planning.",
    category: "investing", icon: "📈", color: "from-green-500 to-emerald-500", popular: true, featured: true, timeToComplete: "2 min",
    tags: ["SIP", "systematic investment plan", "mutual fund", "monthly investment"],
    related: ["lump-sum-calculator", "compound-interest-calculator", "mutual-fund-calculator"],
    seoTitle: "SIP Calculator – Systematic Investment Plan Returns Calculator",
    seoDescription: "Calculate your SIP returns, wealth gain, and future value with our free SIP calculator. Plan your monthly investments today.",
    keywords: ["SIP calculator", "SIP return calculator", "systematic investment plan calculator"],
  },
  {
    id: "step-up-sip", slug: "step-up-sip-calculator", name: "Step-Up SIP Calculator", shortDescription: "SIP with annual increase for accelerated wealth creation",
    description: "Calculate how increasing your monthly SIP amount by a fixed percentage each year dramatically accelerates wealth creation through the power of step-up investing.",
    category: "investing", icon: "📊", color: "from-violet-500 to-purple-600", popular: true, timeToComplete: "2 min",
    tags: ["step-up SIP", "SIP with annual increase", "top-up SIP", "mutual fund", "India"],
    related: ["sip-calculator", "compound-interest-calculator", "lump-sum-calculator"],
    seoTitle: "Step-Up SIP Calculator – Annual Increase SIP Returns",
    seoDescription: "Calculate wealth created with Step-Up SIP (Top-Up SIP). See how increasing your monthly investment by 10-15% annually boosts returns dramatically.",
    keywords: ["step up SIP calculator", "top up SIP", "SIP with annual increase", "step up SIP returns"],
  },
  {
    id: "lump-sum", slug: "lump-sum-calculator", name: "Lump Sum Investment Calculator", shortDescription: "One-time investment growth projections",
    description: "Calculate the future value of a one-time lump sum investment with compound interest over time.",
    category: "investing", icon: "💰", color: "from-blue-500 to-indigo-500", timeToComplete: "2 min",
    tags: ["lump sum", "one-time investment", "compound growth"],
    related: ["sip-calculator", "compound-interest-calculator", "future-value-calculator"],
    seoTitle: "Lump Sum Calculator – One-Time Investment Growth Calculator",
    seoDescription: "Calculate how a lump sum investment grows over time with compound interest. Get future value projections instantly.",
    keywords: ["lump sum calculator", "lump sum investment calculator", "one time investment calculator"],
  },
  {
    id: "compound-interest", slug: "compound-interest-calculator", name: "Compound Interest Calculator", shortDescription: "Watch your money grow exponentially",
    description: "Calculate compound interest with different compounding frequencies: daily, monthly, quarterly, and annually.",
    category: "investing", icon: "🌱", color: "from-teal-500 to-green-500", popular: true, timeToComplete: "2 min",
    tags: ["compound interest", "compounding", "interest calculation"],
    related: ["simple-interest-calculator", "future-value-calculator", "sip-calculator"],
    seoTitle: "Compound Interest Calculator – The Power of Compounding",
    seoDescription: "Calculate compound interest for any investment amount, rate, and time period. See the power of compounding in action.",
    keywords: ["compound interest calculator", "compounding calculator", "interest calculator"],
  },
  {
    id: "investment-return", slug: "investment-return-calculator", name: "Investment Return Calculator", shortDescription: "Calculate total returns on any investment",
    description: "Calculate absolute and annualized returns, ROI, and CAGR for any investment with inflation adjustment.",
    category: "investing", icon: "📊", color: "from-purple-500 to-indigo-500", popular: true, timeToComplete: "2 min",
    tags: ["investment return", "ROI", "CAGR", "annualized return"],
    related: ["cagr-calculator", "annualized-return-calculator", "portfolio-return-calculator"],
    seoTitle: "Investment Return Calculator – ROI and CAGR Calculator",
    seoDescription: "Calculate your investment returns including ROI, CAGR, and inflation-adjusted returns for any time period.",
    keywords: ["investment return calculator", "ROI calculator", "investment calculator"],
  },
  {
    id: "future-value", slug: "future-value-calculator", name: "Future Value Calculator", shortDescription: "Project the future worth of money",
    description: "Calculate the future value of present money, investments, or cash flow streams with compound growth.",
    category: "investing", icon: "🔮", color: "from-violet-500 to-purple-500", timeToComplete: "2 min",
    tags: ["future value", "FV", "time value of money"],
    related: ["present-value-calculator", "compound-interest-calculator", "time-value-calculator"],
    seoTitle: "Future Value Calculator – Project the Worth of Money Over Time",
    seoDescription: "Calculate the future value of money, investments, and cash flows using compound interest formulas.",
    keywords: ["future value calculator", "FV calculator", "future worth calculator"],
  },
  {
    id: "present-value", slug: "present-value-calculator", name: "Present Value Calculator", shortDescription: "Find today's value of future money",
    description: "Calculate the present value of future cash flows using discounting, essential for investment analysis.",
    category: "investing", icon: "⏰", color: "from-sky-500 to-blue-500", timeToComplete: "2 min",
    tags: ["present value", "PV", "discounting", "time value"],
    related: ["future-value-calculator", "npv-calculator", "time-value-calculator"],
    seoTitle: "Present Value Calculator – Discount Future Cash Flows",
    seoDescription: "Calculate the present value of future cash flows with our free PV calculator. Essential for investment and finance decisions.",
    keywords: ["present value calculator", "PV calculator", "discounted cash flow calculator"],
  },
  {
    id: "dca", slug: "dollar-cost-averaging-calculator", name: "Dollar Cost Averaging Calculator", shortDescription: "Average down your investment cost",
    description: "Calculate your average cost and returns using the dollar cost averaging (DCA) investment strategy.",
    category: "investing", icon: "🔄", color: "from-cyan-500 to-teal-500", timeToComplete: "3 min",
    tags: ["dollar cost averaging", "DCA", "average cost"],
    related: ["sip-calculator", "stock-average-calculator", "investment-return-calculator"],
    seoTitle: "Dollar Cost Averaging Calculator – DCA Investment Returns",
    seoDescription: "Calculate returns from dollar cost averaging (DCA) strategy. Find your average cost and total investment value.",
    keywords: ["dollar cost averaging calculator", "DCA calculator", "average cost calculator"],
  },
  {
    id: "dividend", slug: "dividend-calculator", name: "Dividend Calculator", shortDescription: "Calculate dividend income and yield",
    description: "Calculate dividend income, yield, and annual passive income from dividend-paying stocks and funds.",
    category: "investing", icon: "💸", color: "from-green-600 to-green-400", timeToComplete: "2 min",
    tags: ["dividend", "dividend yield", "passive income", "dividend income"],
    related: ["drip-calculator", "portfolio-return-calculator", "investment-return-calculator"],
    seoTitle: "Dividend Calculator – Calculate Dividend Income and Yield",
    seoDescription: "Calculate dividend income, yield, and annual passive income from stocks and dividend funds.",
    keywords: ["dividend calculator", "dividend yield calculator", "dividend income calculator"],
  },
  {
    id: "drip", slug: "drip-calculator", name: "Dividend Reinvestment (DRIP) Calculator", shortDescription: "Compound returns through dividend reinvestment",
    description: "Calculate the power of reinvesting dividends automatically through a DRIP program over time.",
    category: "investing", icon: "♻️", color: "from-emerald-600 to-teal-500", timeToComplete: "3 min",
    tags: ["DRIP", "dividend reinvestment", "compound dividends"],
    related: ["dividend-calculator", "compound-interest-calculator", "investment-return-calculator"],
    seoTitle: "DRIP Calculator – Dividend Reinvestment Plan Calculator",
    seoDescription: "Calculate compound returns from dividend reinvestment (DRIP) programs. See how reinvesting dividends builds wealth.",
    keywords: ["DRIP calculator", "dividend reinvestment calculator", "compound dividend calculator"],
  },
  {
    id: "cagr", slug: "cagr-calculator", name: "CAGR Calculator", shortDescription: "Calculate compound annual growth rate",
    description: "Calculate the Compound Annual Growth Rate (CAGR) of any investment to measure and compare performance.",
    category: "investing", icon: "📐", color: "from-blue-500 to-violet-500", popular: true, timeToComplete: "2 min",
    tags: ["CAGR", "compound annual growth rate", "investment growth"],
    related: ["annualized-return-calculator", "investment-return-calculator", "portfolio-return-calculator"],
    seoTitle: "CAGR Calculator – Compound Annual Growth Rate Calculator",
    seoDescription: "Calculate CAGR (Compound Annual Growth Rate) for any investment. Compare investment performance with ease.",
    keywords: ["CAGR calculator", "compound annual growth rate calculator", "investment growth rate calculator"],
  },
  {
    id: "annualized-return", slug: "annualized-return-calculator", name: "Annualized Return Calculator", shortDescription: "Normalize returns for fair comparison",
    description: "Convert total return into an annualized rate for apples-to-apples comparison of different investments.",
    category: "investing", icon: "📅", color: "from-indigo-500 to-blue-600", timeToComplete: "2 min",
    tags: ["annualized return", "annualized ROI", "annual return"],
    related: ["cagr-calculator", "investment-return-calculator", "portfolio-return-calculator"],
    seoTitle: "Annualized Return Calculator – Normalize Investment Returns",
    seoDescription: "Calculate annualized return to compare investments fairly. Convert any return into a yearly equivalent rate.",
    keywords: ["annualized return calculator", "annual return calculator", "annualized ROI"],
  },
  {
    id: "portfolio-return", slug: "portfolio-return-calculator", name: "Portfolio Return Calculator", shortDescription: "Calculate your total portfolio performance",
    description: "Calculate weighted portfolio returns, tracking multi-asset performance across stocks, bonds, and alternatives.",
    category: "investing", icon: "📦", color: "from-purple-500 to-violet-600", timeToComplete: "4 min",
    tags: ["portfolio return", "portfolio performance", "weighted return"],
    related: ["portfolio-allocation-calculator", "investment-return-calculator", "cagr-calculator"],
    seoTitle: "Portfolio Return Calculator – Multi-Asset Portfolio Performance",
    seoDescription: "Calculate your weighted portfolio return across multiple assets. Track and analyze total portfolio performance.",
    keywords: ["portfolio return calculator", "portfolio performance calculator", "investment portfolio calculator"],
  },
  {
    id: "portfolio-allocation", slug: "portfolio-allocation-calculator", name: "Portfolio Allocation Calculator", shortDescription: "Optimize your asset allocation",
    description: "Design and analyze your ideal asset allocation across stocks, bonds, real estate, and other investments.",
    category: "investing", icon: "🎯", color: "from-rose-500 to-pink-500", featured: true, timeToComplete: "4 min",
    tags: ["asset allocation", "portfolio allocation", "diversification"],
    related: ["portfolio-return-calculator", "risk-reward-calculator", "investment-goal-calculator"],
    seoTitle: "Portfolio Allocation Calculator – Optimize Asset Allocation",
    seoDescription: "Design your optimal portfolio allocation across stocks, bonds, and other assets with risk-return analysis.",
    keywords: ["portfolio allocation calculator", "asset allocation calculator", "investment allocation"],
  },
  {
    id: "etf", slug: "etf-calculator", name: "ETF Investment Calculator", shortDescription: "Model ETF returns with expense ratios",
    description: "Calculate ETF returns accounting for expense ratios, dividend reinvestment, and long-term compound growth.",
    category: "investing", icon: "🏗️", color: "from-blue-400 to-indigo-500", timeToComplete: "3 min",
    tags: ["ETF", "exchange traded fund", "expense ratio", "index fund"],
    related: ["mutual-fund-calculator", "compound-interest-calculator", "sip-calculator"],
    seoTitle: "ETF Calculator – ETF Investment Return Calculator with Expense Ratio",
    seoDescription: "Calculate ETF investment returns accounting for expense ratios, dividends, and compound growth over time.",
    keywords: ["ETF calculator", "ETF return calculator", "index fund calculator"],
  },
  {
    id: "mutual-fund", slug: "mutual-fund-calculator", name: "Mutual Fund Calculator", shortDescription: "Calculate mutual fund investment returns",
    description: "Project mutual fund returns with NAV growth, expense ratio impact, and SIP or lump sum investments.",
    category: "investing", icon: "📁", color: "from-teal-500 to-blue-500", timeToComplete: "3 min",
    tags: ["mutual fund", "NAV", "expense ratio", "fund returns"],
    related: ["sip-calculator", "etf-calculator", "compound-interest-calculator"],
    seoTitle: "Mutual Fund Calculator – Returns with Expense Ratio Impact",
    seoDescription: "Calculate mutual fund returns for SIP and lump sum investments with expense ratio and NAV growth analysis.",
    keywords: ["mutual fund calculator", "mutual fund return calculator", "fund investment calculator"],
  },
  {
    id: "stock-average", slug: "stock-average-calculator", name: "Stock Average Price Calculator", shortDescription: "Calculate your average stock purchase price",
    description: "Calculate the average cost basis of your stock holdings across multiple purchase transactions.",
    category: "investing", icon: "📉", color: "from-red-500 to-rose-500", timeToComplete: "2 min",
    tags: ["stock average", "cost basis", "average down", "stock price"],
    related: ["dca-calculator", "capital-gains-calculator", "investment-return-calculator"],
    seoTitle: "Stock Average Price Calculator – Cost Basis Calculator",
    seoDescription: "Calculate your average stock purchase price and cost basis across multiple transactions. Average down your stock cost.",
    keywords: ["stock average calculator", "average down calculator", "cost basis calculator"],
  },
  {
    id: "capital-gains", slug: "capital-gains-calculator", name: "Capital Gains Calculator", shortDescription: "Calculate profit from selling investments",
    description: "Calculate short-term and long-term capital gains on stocks, real estate, and other investments with tax estimates.",
    category: "investing", icon: "💹", color: "from-green-500 to-teal-600", popular: true, timeToComplete: "3 min",
    tags: ["capital gains", "investment profit", "stock profit", "tax"],
    related: ["capital-gains-tax-calculator", "investment-return-calculator", "income-tax-calculator"],
    seoTitle: "Capital Gains Calculator – Calculate Investment Profits & Tax",
    seoDescription: "Calculate short-term and long-term capital gains on investments with estimated taxes. Plan your investment exits.",
    keywords: ["capital gains calculator", "stock profit calculator", "investment gain calculator"],
  },
  {
    id: "inflation-adjusted-return", slug: "inflation-adjusted-return-calculator", name: "Inflation Adjusted Return Calculator", shortDescription: "Find your real investment returns",
    description: "Calculate your real (inflation-adjusted) investment returns to understand actual purchasing power growth.",
    category: "investing", icon: "📊", color: "from-amber-500 to-yellow-500", timeToComplete: "2 min",
    tags: ["real return", "inflation adjusted", "purchasing power"],
    related: ["inflation-calculator", "investment-return-calculator", "cagr-calculator"],
    seoTitle: "Inflation Adjusted Return Calculator – Real Investment Returns",
    seoDescription: "Calculate real investment returns after inflation adjustment. Find out your actual purchasing power growth.",
    keywords: ["inflation adjusted return calculator", "real return calculator", "inflation investment calculator"],
  },
  {
    id: "risk-reward", slug: "risk-reward-calculator", name: "Risk vs Reward Calculator", shortDescription: "Evaluate investment risk-return tradeoff",
    description: "Analyze the risk-return profile of investments with Sharpe ratio, standard deviation, and scenario analysis.",
    category: "investing", icon: "⚖️", color: "from-violet-500 to-purple-600", timeToComplete: "3 min",
    tags: ["risk reward", "Sharpe ratio", "risk analysis", "investment risk"],
    related: ["portfolio-allocation-calculator", "portfolio-return-calculator", "investment-goal-calculator"],
    seoTitle: "Risk vs Reward Calculator – Sharpe Ratio & Risk Analysis",
    seoDescription: "Calculate risk-return tradeoff, Sharpe ratio, and analyze investment risk profiles with scenario analysis.",
    keywords: ["risk reward calculator", "Sharpe ratio calculator", "investment risk calculator"],
  },
  {
    id: "investment-goal", slug: "investment-goal-calculator", name: "Investment Goal Calculator", shortDescription: "Plan contributions to reach your investment target",
    description: "Calculate how much to invest monthly to reach a specific financial goal by a target date.",
    category: "investing", icon: "🏁", color: "from-cyan-500 to-sky-500", timeToComplete: "3 min",
    tags: ["investment goal", "target corpus", "goal planning"],
    related: ["savings-goal-calculator", "sip-calculator", "compound-interest-calculator"],
    seoTitle: "Investment Goal Calculator – How Much to Invest to Reach Your Goal",
    seoDescription: "Calculate monthly investment needed to reach your financial goal. Plan your investment strategy for any target amount.",
    keywords: ["investment goal calculator", "goal based investing", "target corpus calculator"],
  },

  // REAL ESTATE
  {
    id: "mortgage", slug: "mortgage-calculator", name: "Mortgage Calculator", shortDescription: "Calculate monthly mortgage payments",
    description: "Calculate monthly mortgage payments, total interest, amortization schedule, and full loan breakdown.",
    category: "real-estate", icon: "🏠", color: "from-purple-500 to-violet-500", popular: true, featured: true, timeToComplete: "3 min",
    tags: ["mortgage", "home loan", "monthly payment", "amortization"],
    related: ["mortgage-affordability-calculator", "mortgage-payoff-calculator", "home-equity-calculator"],
    seoTitle: "Mortgage Calculator – Monthly Payment & Amortization Schedule",
    seoDescription: "Calculate your monthly mortgage payment, total interest paid, and full amortization schedule. Free mortgage calculator.",
    keywords: ["mortgage calculator", "home loan calculator", "monthly mortgage payment calculator"],
  },
  {
    id: "mortgage-affordability", slug: "mortgage-affordability-calculator", name: "Mortgage Affordability Calculator", shortDescription: "How much house can you afford?",
    description: "Calculate the maximum home price you can afford based on income, debts, down payment, and lender guidelines.",
    category: "real-estate", icon: "🏡", color: "from-indigo-500 to-purple-500", popular: true, timeToComplete: "4 min",
    tags: ["mortgage affordability", "home buying", "how much house"],
    related: ["mortgage-calculator", "debt-to-income-calculator", "closing-cost-calculator"],
    seoTitle: "Mortgage Affordability Calculator – How Much House Can You Afford?",
    seoDescription: "Calculate how much house you can afford based on income, debts, and down payment. Use the 28/36 rule for guidance.",
    keywords: ["mortgage affordability calculator", "home affordability calculator", "how much house can I afford"],
  },
  {
    id: "mortgage-payoff", slug: "mortgage-payoff-calculator", name: "Mortgage Payoff Calculator", shortDescription: "Pay off your mortgage faster",
    description: "Calculate how extra payments can help you pay off your mortgage early and save thousands in interest.",
    category: "real-estate", icon: "🔓", color: "from-teal-500 to-green-500", timeToComplete: "3 min",
    tags: ["mortgage payoff", "early payoff", "extra payments"],
    related: ["mortgage-calculator", "home-equity-calculator", "debt-snowball-calculator"],
    seoTitle: "Mortgage Payoff Calculator – Pay Off Your Home Loan Faster",
    seoDescription: "Calculate how extra mortgage payments reduce your payoff date and save money on interest. Plan your early mortgage payoff.",
    keywords: ["mortgage payoff calculator", "early mortgage payoff calculator", "extra mortgage payment calculator"],
  },
  {
    id: "rental-yield", slug: "rental-yield-calculator", name: "Rental Yield Calculator", shortDescription: "Calculate gross and net rental yield",
    description: "Calculate gross and net rental yield on investment properties to evaluate rental income potential.",
    category: "real-estate", icon: "🏢", color: "from-amber-500 to-orange-500", timeToComplete: "3 min",
    tags: ["rental yield", "rental property", "property investment", "gross yield"],
    related: ["rental-roi-calculator", "cap-rate-calculator", "cash-flow-calculator"],
    seoTitle: "Rental Yield Calculator – Gross and Net Rental Yield",
    seoDescription: "Calculate rental yield on investment properties. Compare gross and net yield to evaluate property investments.",
    keywords: ["rental yield calculator", "property yield calculator", "rental return calculator"],
  },
  {
    id: "rental-roi", slug: "rental-roi-calculator", name: "Rental ROI Calculator", shortDescription: "Total return on rental property investment",
    description: "Calculate comprehensive ROI on rental properties including cash flow, appreciation, and equity buildup.",
    category: "real-estate", icon: "📊", color: "from-rose-500 to-red-500", timeToComplete: "4 min",
    tags: ["rental ROI", "investment property", "real estate ROI"],
    related: ["rental-yield-calculator", "cap-rate-calculator", "cash-on-cash-calculator"],
    seoTitle: "Rental ROI Calculator – Real Estate Investment Return Calculator",
    seoDescription: "Calculate total ROI on rental properties including cash flow, appreciation, equity, and tax benefits.",
    keywords: ["rental ROI calculator", "rental property ROI calculator", "real estate ROI calculator"],
  },
  {
    id: "cash-flow", slug: "cash-flow-calculator", name: "Cash Flow Calculator", shortDescription: "Analyze rental property cash flow",
    description: "Calculate monthly and annual cash flow from rental properties after all expenses, mortgage, and vacancies.",
    category: "real-estate", icon: "💧", color: "from-blue-500 to-cyan-500", timeToComplete: "4 min",
    tags: ["cash flow", "rental cash flow", "NOI", "real estate"],
    related: ["cap-rate-calculator", "rental-roi-calculator", "rental-yield-calculator"],
    seoTitle: "Cash Flow Calculator – Rental Property Cash Flow Analysis",
    seoDescription: "Calculate rental property cash flow after expenses, mortgage, vacancy, and maintenance costs.",
    keywords: ["cash flow calculator", "rental cash flow calculator", "property cash flow"],
  },
  {
    id: "cap-rate", slug: "cap-rate-calculator", name: "Cap Rate Calculator", shortDescription: "Evaluate property with capitalization rate",
    description: "Calculate the capitalization rate (cap rate) to evaluate and compare real estate investment opportunities.",
    category: "real-estate", icon: "🏗️", color: "from-slate-500 to-blue-500", timeToComplete: "2 min",
    tags: ["cap rate", "capitalization rate", "NOI", "property valuation"],
    related: ["cash-flow-calculator", "rental-roi-calculator", "rental-yield-calculator"],
    seoTitle: "Cap Rate Calculator – Real Estate Capitalization Rate",
    seoDescription: "Calculate cap rate for rental properties to evaluate investment value and compare real estate opportunities.",
    keywords: ["cap rate calculator", "capitalization rate calculator", "real estate cap rate"],
  },
  {
    id: "cash-on-cash", slug: "cash-on-cash-calculator", name: "Cash-on-Cash Return Calculator", shortDescription: "Annual return on your cash invested",
    description: "Calculate cash-on-cash return to measure annual pre-tax cash income relative to cash invested in property.",
    category: "real-estate", icon: "💵", color: "from-green-500 to-emerald-600", timeToComplete: "3 min",
    tags: ["cash on cash return", "CoC", "property ROI", "real estate"],
    related: ["cap-rate-calculator", "rental-roi-calculator", "cash-flow-calculator"],
    seoTitle: "Cash-on-Cash Return Calculator – Real Estate Investment Analysis",
    seoDescription: "Calculate cash-on-cash (CoC) return on real estate investments. Measure annual cash income vs total cash invested.",
    keywords: ["cash on cash return calculator", "CoC calculator", "real estate cash return"],
  },
  {
    id: "property-tax", slug: "property-tax-calculator", name: "Property Tax Calculator", shortDescription: "Estimate your annual property taxes",
    description: "Estimate annual property taxes based on assessed value, mill rate, and local tax exemptions.",
    category: "real-estate", icon: "🏛️", color: "from-yellow-500 to-amber-500", timeToComplete: "2 min",
    tags: ["property tax", "real estate tax", "mill rate"],
    related: ["mortgage-calculator", "closing-cost-calculator", "home-equity-calculator"],
    seoTitle: "Property Tax Calculator – Estimate Annual Property Taxes",
    seoDescription: "Estimate your annual property tax bill based on home value, assessment rate, and local mill rate.",
    keywords: ["property tax calculator", "real estate tax calculator", "home tax calculator"],
  },
  {
    id: "closing-cost", slug: "closing-cost-calculator", name: "Closing Cost Calculator", shortDescription: "Estimate home buying closing costs",
    description: "Estimate total closing costs when buying a home, including lender fees, title insurance, and prepaid items.",
    category: "real-estate", icon: "📝", color: "from-violet-500 to-indigo-500", timeToComplete: "3 min",
    tags: ["closing costs", "home buying", "mortgage fees"],
    related: ["mortgage-calculator", "mortgage-affordability-calculator", "property-tax-calculator"],
    seoTitle: "Closing Cost Calculator – Estimate Home Purchase Closing Costs",
    seoDescription: "Estimate total closing costs when buying a home. Calculate lender fees, title insurance, and prepaid expenses.",
    keywords: ["closing cost calculator", "home closing cost calculator", "mortgage closing costs"],
  },
  {
    id: "mortgage-refinance", slug: "mortgage-refinance-calculator", name: "Mortgage Refinance Calculator", shortDescription: "Should you refinance your mortgage?",
    description: "Calculate if refinancing makes sense: new payment, break-even point, lifetime savings, and comparison.",
    category: "real-estate", icon: "🔁", color: "from-cyan-500 to-blue-500", timeToComplete: "4 min",
    tags: ["mortgage refinance", "refinancing", "break-even", "rate comparison"],
    related: ["mortgage-calculator", "mortgage-payoff-calculator", "home-equity-calculator"],
    seoTitle: "Mortgage Refinance Calculator – Should You Refinance?",
    seoDescription: "Calculate mortgage refinance savings, break-even period, and total interest savings vs your current loan.",
    keywords: ["mortgage refinance calculator", "refinance calculator", "should I refinance"],
  },
  {
    id: "home-equity", slug: "home-equity-calculator", name: "Home Equity Calculator", shortDescription: "Calculate your home equity and LTV",
    description: "Calculate your current home equity, loan-to-value ratio, and potential for a home equity loan or HELOC.",
    category: "real-estate", icon: "🏠", color: "from-emerald-500 to-teal-500", timeToComplete: "2 min",
    tags: ["home equity", "LTV", "HELOC", "equity"],
    related: ["mortgage-calculator", "mortgage-refinance-calculator", "mortgage-payoff-calculator"],
    seoTitle: "Home Equity Calculator – Calculate Your Equity and LTV Ratio",
    seoDescription: "Calculate your home equity, loan-to-value (LTV) ratio, and HELOC eligibility based on current home value.",
    keywords: ["home equity calculator", "equity calculator", "LTV calculator"],
  },

  // LOANS
  {
    id: "emi", slug: "emi-calculator", name: "EMI Calculator", shortDescription: "Calculate loan EMI and amortization",
    description: "Calculate EMI (Equated Monthly Installment) for any loan with full amortization schedule and interest breakdown.",
    category: "loans", icon: "💳", color: "from-rose-500 to-pink-500", popular: true, featured: true, timeToComplete: "2 min",
    tags: ["EMI", "loan payment", "monthly installment", "amortization"],
    related: ["personal-loan-calculator", "home-loan-calculator", "car-loan-calculator"],
    seoTitle: "EMI Calculator – Calculate Loan EMI & Amortization Schedule",
    seoDescription: "Calculate EMI for any loan instantly. Get monthly installment, total interest, and complete amortization schedule.",
    keywords: ["EMI calculator", "loan EMI calculator", "monthly payment calculator"],
  },
  {
    id: "personal-loan", slug: "personal-loan-calculator", name: "Personal Loan Calculator", shortDescription: "Compare personal loan options",
    description: "Calculate personal loan payments, compare lenders, and find the true cost of borrowing.",
    category: "loans", icon: "👤", color: "from-blue-500 to-indigo-500", timeToComplete: "2 min",
    tags: ["personal loan", "unsecured loan", "loan comparison"],
    related: ["emi-calculator", "loan-comparison-calculator", "debt-to-income-calculator"],
    seoTitle: "Personal Loan Calculator – Monthly Payment & Total Cost",
    seoDescription: "Calculate personal loan monthly payments, total interest, and compare different loan options.",
    keywords: ["personal loan calculator", "loan payment calculator", "personal loan EMI"],
  },
  {
    id: "home-loan", slug: "home-loan-calculator", name: "Home Loan Calculator", shortDescription: "Calculate home loan payments and interest",
    description: "Calculate home loan EMI, interest, and total cost with prepayment options and comparison tools.",
    category: "loans", icon: "🏠", color: "from-purple-500 to-violet-500", timeToComplete: "3 min",
    tags: ["home loan", "housing loan", "mortgage EMI"],
    related: ["mortgage-calculator", "emi-calculator", "mortgage-affordability-calculator"],
    seoTitle: "Home Loan Calculator – EMI, Interest & Amortization",
    seoDescription: "Calculate home loan EMI, total interest payable, and amortization schedule with prepayment impact analysis.",
    keywords: ["home loan calculator", "housing loan calculator", "home loan EMI calculator"],
  },
  {
    id: "car-loan", slug: "car-loan-calculator", name: "Car Loan Calculator", shortDescription: "Calculate auto loan payments",
    description: "Calculate car loan monthly payments, total cost of ownership, and compare financing vs paying cash.",
    category: "loans", icon: "🚗", color: "from-slate-600 to-blue-500", timeToComplete: "2 min",
    tags: ["car loan", "auto loan", "vehicle financing"],
    related: ["emi-calculator", "personal-loan-calculator", "loan-comparison-calculator"],
    seoTitle: "Car Loan Calculator – Auto Loan Monthly Payment Calculator",
    seoDescription: "Calculate car loan monthly payments, total interest, and compare financing options for your next vehicle.",
    keywords: ["car loan calculator", "auto loan calculator", "vehicle loan calculator"],
  },
  {
    id: "student-loan", slug: "student-loan-calculator", name: "Student Loan Calculator", shortDescription: "Plan student loan repayment",
    description: "Calculate student loan monthly payments, repayment timelines, and compare income-driven repayment options.",
    category: "loans", icon: "🎓", color: "from-amber-500 to-yellow-500", timeToComplete: "3 min",
    tags: ["student loan", "student debt", "loan repayment", "IBR"],
    related: ["emi-calculator", "debt-avalanche-calculator", "debt-snowball-calculator"],
    seoTitle: "Student Loan Calculator – Repayment & Payoff Planning",
    seoDescription: "Calculate student loan monthly payments, total cost, and compare repayment plans including income-driven options.",
    keywords: ["student loan calculator", "student loan repayment calculator", "college loan calculator"],
  },
  {
    id: "business-loan", slug: "business-loan-calculator", name: "Business Loan Calculator", shortDescription: "Calculate business financing costs",
    description: "Calculate business loan payments, effective APR, and total financing cost for business decisions.",
    category: "loans", icon: "💼", color: "from-indigo-500 to-blue-600", timeToComplete: "3 min",
    tags: ["business loan", "SBA loan", "commercial loan", "APR"],
    related: ["emi-calculator", "roi-calculator", "break-even-calculator"],
    seoTitle: "Business Loan Calculator – Monthly Payment & Total Cost",
    seoDescription: "Calculate business loan payments, effective APR, and total cost for SBA and commercial loan decisions.",
    keywords: ["business loan calculator", "commercial loan calculator", "SBA loan calculator"],
  },
  {
    id: "credit-card-payoff", slug: "credit-card-payoff-calculator", name: "Credit Card Payoff Calculator", shortDescription: "Get out of credit card debt faster",
    description: "Calculate how long to pay off credit card debt and find the optimal payment strategy to minimize interest.",
    category: "loans", icon: "💳", color: "from-red-500 to-rose-600", popular: true, timeToComplete: "3 min",
    tags: ["credit card payoff", "credit card debt", "debt elimination"],
    related: ["debt-snowball-calculator", "debt-avalanche-calculator", "loan-comparison-calculator"],
    seoTitle: "Credit Card Payoff Calculator – Eliminate Credit Card Debt",
    seoDescription: "Calculate when you'll be debt-free and how much interest you'll save with different credit card payment strategies.",
    keywords: ["credit card payoff calculator", "credit card debt calculator", "pay off credit card calculator"],
  },
  {
    id: "debt-snowball", slug: "debt-snowball-calculator", name: "Debt Snowball Calculator", shortDescription: "Pay smallest debts first for motivation",
    description: "Apply the debt snowball method to pay off multiple debts by focusing on smallest balances first.",
    category: "loans", icon: "❄️", color: "from-blue-400 to-cyan-500", timeToComplete: "4 min",
    tags: ["debt snowball", "debt payoff", "multiple debts"],
    related: ["debt-avalanche-calculator", "credit-card-payoff-calculator", "loan-comparison-calculator"],
    seoTitle: "Debt Snowball Calculator – Pay Off Debt Using the Snowball Method",
    seoDescription: "Use the debt snowball method to pay off multiple debts. Calculate payoff order, timeline, and total interest saved.",
    keywords: ["debt snowball calculator", "snowball method calculator", "debt payoff calculator"],
  },
  {
    id: "debt-avalanche", slug: "debt-avalanche-calculator", name: "Debt Avalanche Calculator", shortDescription: "Pay highest-interest debts first",
    description: "Apply the debt avalanche method to minimize total interest paid while eliminating multiple debts faster.",
    category: "loans", icon: "🏔️", color: "from-violet-500 to-purple-600", timeToComplete: "4 min",
    tags: ["debt avalanche", "highest interest first", "debt optimization"],
    related: ["debt-snowball-calculator", "credit-card-payoff-calculator", "loan-comparison-calculator"],
    seoTitle: "Debt Avalanche Calculator – Minimize Interest with Avalanche Method",
    seoDescription: "Use the debt avalanche method to pay off debt while minimizing total interest paid. Compare with snowball method.",
    keywords: ["debt avalanche calculator", "avalanche method calculator", "pay off debt calculator"],
  },
  {
    id: "loan-comparison", slug: "loan-comparison-calculator", name: "Loan Comparison Calculator", shortDescription: "Compare multiple loan options side-by-side",
    description: "Compare up to 4 loans side-by-side with monthly payment, total interest, and APR analysis.",
    category: "loans", icon: "⚖️", color: "from-teal-500 to-cyan-500", timeToComplete: "4 min",
    tags: ["loan comparison", "compare loans", "loan shopping"],
    related: ["emi-calculator", "personal-loan-calculator", "mortgage-calculator"],
    seoTitle: "Loan Comparison Calculator – Compare Multiple Loans Side-by-Side",
    seoDescription: "Compare multiple loan offers side-by-side. Analyze monthly payments, total interest, and APR to choose the best loan.",
    keywords: ["loan comparison calculator", "compare loans calculator", "best loan calculator"],
  },

  // SAVINGS
  {
    id: "savings-goal", slug: "savings-goal-calculator", name: "Savings Goal Calculator", shortDescription: "Plan how to reach any savings target",
    description: "Calculate how long to reach any savings goal and the monthly contribution needed to get there.",
    category: "savings", icon: "🎯", color: "from-teal-500 to-cyan-500", popular: true, timeToComplete: "2 min",
    tags: ["savings goal", "target savings", "monthly savings"],
    related: ["emergency-fund-calculator", "investment-goal-calculator", "compound-interest-calculator"],
    seoTitle: "Savings Goal Calculator – How to Reach Any Financial Goal",
    seoDescription: "Calculate monthly savings needed to reach any financial goal. Plan savings for vacation, car, down payment, and more.",
    keywords: ["savings goal calculator", "savings target calculator", "how much to save calculator"],
  },
  {
    id: "emergency-fund", slug: "emergency-fund-calculator", name: "Emergency Fund Calculator", shortDescription: "Find your ideal emergency fund size",
    description: "Calculate the ideal emergency fund size based on your monthly expenses, job stability, and financial situation.",
    category: "savings", icon: "🛟", color: "from-orange-500 to-amber-500", timeToComplete: "2 min",
    tags: ["emergency fund", "rainy day fund", "financial safety net"],
    related: ["savings-goal-calculator", "budget-planner", "net-worth-calculator"],
    seoTitle: "Emergency Fund Calculator – How Much Should You Save?",
    seoDescription: "Calculate the ideal emergency fund size based on your monthly expenses, job type, and financial obligations.",
    keywords: ["emergency fund calculator", "emergency savings calculator", "rainy day fund calculator"],
  },
  {
    id: "high-yield-savings", slug: "high-yield-savings-calculator", name: "High-Yield Savings Calculator", shortDescription: "Maximize savings account returns",
    description: "Calculate and compare high-yield savings account returns vs traditional savings accounts.",
    category: "savings", icon: "💰", color: "from-yellow-500 to-green-500", timeToComplete: "2 min",
    tags: ["HYSA", "high yield savings", "savings account APY"],
    related: ["savings-goal-calculator", "compound-interest-calculator", "fixed-deposit-calculator"],
    seoTitle: "High-Yield Savings Calculator – HYSA Returns vs Traditional Savings",
    seoDescription: "Calculate high-yield savings account returns and compare with traditional savings. Maximize your savings interest.",
    keywords: ["high yield savings calculator", "HYSA calculator", "savings account calculator"],
  },
  {
    id: "fixed-deposit", slug: "fixed-deposit-calculator", name: "Fixed Deposit Calculator", shortDescription: "Calculate FD maturity and interest",
    description: "Calculate fixed deposit maturity amount, interest earned, and effective yield with different compounding options.",
    category: "savings", icon: "🔒", color: "from-blue-500 to-indigo-500", timeToComplete: "2 min",
    tags: ["fixed deposit", "FD", "term deposit", "CD"],
    related: ["recurring-deposit-calculator", "compound-interest-calculator", "high-yield-savings-calculator"],
    seoTitle: "Fixed Deposit Calculator – FD Maturity Amount & Interest",
    seoDescription: "Calculate fixed deposit maturity amount and total interest earned for any FD tenure and interest rate.",
    keywords: ["fixed deposit calculator", "FD calculator", "term deposit calculator"],
  },
  {
    id: "recurring-deposit", slug: "recurring-deposit-calculator", name: "Recurring Deposit Calculator", shortDescription: "Monthly deposit maturity calculator",
    description: "Calculate the maturity value of recurring deposits with monthly contributions and compound interest.",
    category: "savings", icon: "🔄", color: "from-teal-500 to-green-500", timeToComplete: "2 min",
    tags: ["recurring deposit", "RD", "monthly savings"],
    related: ["fixed-deposit-calculator", "sip-calculator", "savings-goal-calculator"],
    seoTitle: "Recurring Deposit Calculator – RD Maturity & Interest",
    seoDescription: "Calculate recurring deposit maturity amount and interest earned for monthly savings contributions.",
    keywords: ["recurring deposit calculator", "RD calculator", "monthly deposit calculator"],
  },
  {
    id: "time-value", slug: "time-value-calculator", name: "Time Value of Money Calculator", shortDescription: "Master the foundation of finance",
    description: "Comprehensive time value of money calculator covering PV, FV, PMT, rate, and periods with interactive timeline.",
    category: "savings", icon: "⏳", color: "from-purple-500 to-indigo-500", timeToComplete: "3 min",
    tags: ["time value of money", "TVM", "PV", "FV", "annuity"],
    related: ["present-value-calculator", "future-value-calculator", "compound-interest-calculator"],
    seoTitle: "Time Value of Money Calculator – PV, FV, Rate & Periods",
    seoDescription: "Calculate any time value of money variable: present value, future value, payment, rate, or periods.",
    keywords: ["time value of money calculator", "TVM calculator", "annuity calculator"],
  },

  // TAXES
  {
    id: "income-tax", slug: "income-tax-calculator", name: "Income Tax Calculator", shortDescription: "Estimate your federal and state income tax",
    description: "Estimate federal and state income tax liability with deductions, credits, and effective tax rate.",
    category: "taxes", icon: "📊", color: "from-yellow-500 to-amber-500", popular: true, featured: true, timeToComplete: "4 min",
    tags: ["income tax", "federal tax", "state tax", "tax liability"],
    related: ["capital-gains-tax-calculator", "self-employment-tax-calculator", "take-home-pay-calculator"],
    seoTitle: "Income Tax Calculator 2024 – Federal & State Tax Estimator",
    seoDescription: "Estimate your 2024 federal and state income tax liability with deductions and credits. Find your effective tax rate.",
    keywords: ["income tax calculator", "tax calculator 2024", "federal tax calculator"],
  },
  {
    id: "capital-gains-tax", slug: "capital-gains-tax-calculator", name: "Capital Gains Tax Calculator", shortDescription: "Tax on investment profits",
    description: "Calculate capital gains tax on stocks, real estate, and other assets with short-term vs long-term rates.",
    category: "taxes", icon: "💰", color: "from-amber-500 to-orange-500", timeToComplete: "3 min",
    tags: ["capital gains tax", "investment tax", "short term long term"],
    related: ["capital-gains-calculator", "income-tax-calculator", "crypto-tax-calculator"],
    seoTitle: "Capital Gains Tax Calculator – Short & Long-Term Tax Rates",
    seoDescription: "Calculate capital gains tax on investments. Compare short-term vs long-term rates and plan tax-efficient exits.",
    keywords: ["capital gains tax calculator", "investment tax calculator", "stock tax calculator"],
  },
  {
    id: "sales-tax", slug: "sales-tax-calculator", name: "Sales Tax Calculator", shortDescription: "Add or remove sales tax from prices",
    description: "Calculate sales tax for any US state, add tax to prices, or reverse-calculate tax-exclusive amounts.",
    category: "taxes", icon: "🏪", color: "from-green-500 to-teal-500", timeToComplete: "1 min",
    tags: ["sales tax", "state tax", "purchase tax"],
    related: ["vat-calculator", "income-tax-calculator"],
    seoTitle: "Sales Tax Calculator – Add or Remove Tax from Any Price",
    seoDescription: "Calculate sales tax for any US state. Add tax to prices or reverse-calculate the pre-tax amount.",
    keywords: ["sales tax calculator", "state sales tax calculator", "tax calculator"],
  },
  {
    id: "vat", slug: "vat-calculator", name: "VAT Calculator", shortDescription: "Calculate Value Added Tax",
    description: "Calculate VAT for multiple countries, add or remove VAT from prices, and calculate net and gross amounts.",
    category: "taxes", icon: "🌍", color: "from-blue-500 to-indigo-500", timeToComplete: "1 min",
    tags: ["VAT", "value added tax", "GST", "tax inclusive"],
    related: ["sales-tax-calculator", "income-tax-calculator"],
    seoTitle: "VAT Calculator – Calculate Value Added Tax (VAT/GST)",
    seoDescription: "Calculate VAT for any country or rate. Add or remove VAT from prices with gross and net amount breakdown.",
    keywords: ["VAT calculator", "value added tax calculator", "GST calculator"],
  },
  {
    id: "self-employment-tax", slug: "self-employment-tax-calculator", name: "Self-Employment Tax Calculator", shortDescription: "Calculate SE tax for freelancers",
    description: "Calculate self-employment tax (Social Security + Medicare) for freelancers, contractors, and small business owners.",
    category: "taxes", icon: "💻", color: "from-violet-500 to-purple-500", timeToComplete: "2 min",
    tags: ["self employment tax", "freelancer tax", "1099 tax"],
    related: ["income-tax-calculator", "take-home-pay-calculator", "salary-calculator"],
    seoTitle: "Self-Employment Tax Calculator – Freelancer & 1099 Tax",
    seoDescription: "Calculate self-employment tax (SE tax) for freelancers and contractors including Social Security and Medicare.",
    keywords: ["self employment tax calculator", "freelancer tax calculator", "1099 tax calculator"],
  },
  {
    id: "crypto-tax", slug: "crypto-tax-calculator", name: "Crypto Tax Estimator", shortDescription: "Estimate cryptocurrency tax liability",
    description: "Estimate cryptocurrency capital gains tax using FIFO, LIFO, or average cost basis methods.",
    category: "taxes", icon: "₿", color: "from-orange-500 to-yellow-500", timeToComplete: "3 min",
    tags: ["crypto tax", "bitcoin tax", "cryptocurrency capital gains"],
    related: ["capital-gains-tax-calculator", "capital-gains-calculator", "income-tax-calculator"],
    seoTitle: "Crypto Tax Calculator – Cryptocurrency Capital Gains Tax",
    seoDescription: "Estimate crypto capital gains tax using FIFO, LIFO, or average cost methods for Bitcoin, Ethereum, and more.",
    keywords: ["crypto tax calculator", "cryptocurrency tax calculator", "bitcoin tax calculator"],
  },

  // BUSINESS
  {
    id: "roi", slug: "roi-calculator", name: "ROI Calculator", shortDescription: "Calculate return on investment",
    description: "Calculate ROI for any business investment, marketing campaign, or financial decision with annualized returns.",
    category: "business", icon: "📈", color: "from-indigo-500 to-blue-500", popular: true, timeToComplete: "2 min",
    tags: ["ROI", "return on investment", "business ROI"],
    related: ["irr-calculator", "npv-calculator", "break-even-calculator"],
    seoTitle: "ROI Calculator – Return on Investment Calculator",
    seoDescription: "Calculate ROI for any investment or business decision. Get simple ROI, annualized ROI, and profitability analysis.",
    keywords: ["ROI calculator", "return on investment calculator", "business ROI calculator"],
  },
  {
    id: "irr", slug: "irr-calculator", name: "IRR Calculator", shortDescription: "Internal rate of return for investments",
    description: "Calculate the Internal Rate of Return (IRR) for a series of cash flows to evaluate investment viability.",
    category: "business", icon: "📉", color: "from-purple-500 to-violet-500", timeToComplete: "3 min",
    tags: ["IRR", "internal rate of return", "cash flows"],
    related: ["npv-calculator", "roi-calculator", "break-even-calculator"],
    seoTitle: "IRR Calculator – Internal Rate of Return Calculator",
    seoDescription: "Calculate Internal Rate of Return (IRR) for any investment or project with a series of cash flows.",
    keywords: ["IRR calculator", "internal rate of return calculator", "investment IRR"],
  },
  {
    id: "npv", slug: "npv-calculator", name: "NPV Calculator", shortDescription: "Net present value of cash flows",
    description: "Calculate Net Present Value (NPV) of an investment to determine if it creates or destroys value.",
    category: "business", icon: "💡", color: "from-cyan-500 to-blue-500", timeToComplete: "3 min",
    tags: ["NPV", "net present value", "discounted cash flow"],
    related: ["irr-calculator", "present-value-calculator", "roi-calculator"],
    seoTitle: "NPV Calculator – Net Present Value Calculator",
    seoDescription: "Calculate Net Present Value (NPV) of investment cash flows. Determine if a project or investment creates value.",
    keywords: ["NPV calculator", "net present value calculator", "DCF calculator"],
  },
  {
    id: "break-even", slug: "break-even-calculator", name: "Break-even Calculator", shortDescription: "Find your business break-even point",
    description: "Calculate break-even point in units and revenue for any business or product with contribution margin analysis.",
    category: "business", icon: "⚖️", color: "from-teal-500 to-green-500", timeToComplete: "3 min",
    tags: ["break even", "break-even analysis", "fixed costs", "contribution margin"],
    related: ["roi-calculator", "profit-margin-calculator", "revenue-growth-calculator"],
    seoTitle: "Break-Even Calculator – Break-Even Point Analysis",
    seoDescription: "Calculate break-even point in units and revenue. Analyze fixed costs, variable costs, and contribution margin.",
    keywords: ["break even calculator", "break-even analysis calculator", "break even point calculator"],
  },
  {
    id: "profit-margin", slug: "profit-margin-calculator", name: "Profit Margin Calculator", shortDescription: "Calculate gross and net profit margins",
    description: "Calculate gross, operating, and net profit margins with markup conversion and competitive benchmarking.",
    category: "business", icon: "💸", color: "from-green-500 to-emerald-600", timeToComplete: "2 min",
    tags: ["profit margin", "gross margin", "net margin", "markup"],
    related: ["markup-calculator", "roi-calculator", "break-even-calculator"],
    seoTitle: "Profit Margin Calculator – Gross, Operating & Net Margin",
    seoDescription: "Calculate gross profit margin, operating margin, and net profit margin. Convert between margin and markup.",
    keywords: ["profit margin calculator", "gross margin calculator", "net profit margin calculator"],
  },
  {
    id: "markup", slug: "markup-calculator", name: "Markup Calculator", shortDescription: "Calculate price markup from cost",
    description: "Calculate selling price from cost and desired markup, or find the markup percentage from cost and price.",
    category: "business", icon: "🏷️", color: "from-amber-500 to-orange-500", timeToComplete: "2 min",
    tags: ["markup", "markup percentage", "pricing", "profit"],
    related: ["profit-margin-calculator", "roi-calculator", "break-even-calculator"],
    seoTitle: "Markup Calculator – Calculate Selling Price from Cost",
    seoDescription: "Calculate markup percentage, selling price from cost, or reverse-calculate cost from price and markup.",
    keywords: ["markup calculator", "markup percentage calculator", "price markup calculator"],
  },
  {
    id: "revenue-growth", slug: "revenue-growth-calculator", name: "Revenue Growth Calculator", shortDescription: "Track and project revenue growth",
    description: "Calculate revenue growth rate, project future revenue, and analyze compound annual growth for businesses.",
    category: "business", icon: "📊", color: "from-blue-500 to-cyan-500", timeToComplete: "2 min",
    tags: ["revenue growth", "MoM growth", "YoY growth", "CAGR"],
    related: ["cagr-calculator", "roi-calculator", "business-valuation-calculator"],
    seoTitle: "Revenue Growth Calculator – MoM and YoY Growth Rate",
    seoDescription: "Calculate monthly, quarterly, and annual revenue growth rates. Project future revenue with compound growth.",
    keywords: ["revenue growth calculator", "growth rate calculator", "business growth calculator"],
  },
  {
    id: "business-valuation", slug: "business-valuation-calculator", name: "Business Valuation Calculator", shortDescription: "Estimate your business value",
    description: "Estimate business value using multiple methods: P/E ratio, EBITDA multiples, DCF, and asset-based valuation.",
    category: "business", icon: "🏢", color: "from-slate-600 to-indigo-500", timeToComplete: "5 min",
    tags: ["business valuation", "company value", "EBITDA multiple"],
    related: ["irr-calculator", "npv-calculator", "roi-calculator"],
    seoTitle: "Business Valuation Calculator – Estimate Company Value",
    seoDescription: "Estimate business value using P/E, EBITDA, DCF, and asset methods. Professional business valuation tool.",
    keywords: ["business valuation calculator", "company valuation calculator", "business worth calculator"],
  },

  // PERSONAL FINANCE
  {
    id: "budget-planner", slug: "budget-planner-calculator", name: "Budget Planner", shortDescription: "Build and manage your monthly budget",
    description: "Create a comprehensive monthly budget with income, expenses, savings targets, and the 50/30/20 rule.",
    category: "personal-finance", icon: "📋", color: "from-slate-500 to-gray-500", popular: true, featured: true, timeToComplete: "5 min",
    tags: ["budget", "budgeting", "50/30/20 rule", "expense tracking"],
    related: ["net-worth-calculator", "savings-goal-calculator", "emergency-fund-calculator"],
    seoTitle: "Budget Planner – Monthly Budget Calculator with 50/30/20 Rule",
    seoDescription: "Plan your monthly budget with the 50/30/20 rule. Track income, expenses, and savings with visual breakdowns.",
    keywords: ["budget planner", "budget calculator", "monthly budget calculator"],
  },
  {
    id: "net-worth", slug: "net-worth-calculator", name: "Net Worth Calculator", shortDescription: "Calculate your total financial picture",
    description: "Calculate your complete net worth by totaling all assets and liabilities with tracking over time.",
    category: "personal-finance", icon: "💎", color: "from-purple-500 to-pink-500", popular: true, timeToComplete: "5 min",
    tags: ["net worth", "assets", "liabilities", "wealth"],
    related: ["budget-planner", "fire-progress-tracker", "financial-independence-calculator"],
    seoTitle: "Net Worth Calculator – Calculate Your Total Wealth",
    seoDescription: "Calculate your net worth by totaling assets minus liabilities. Track your wealth-building progress over time.",
    keywords: ["net worth calculator", "wealth calculator", "assets and liabilities calculator"],
  },
  {
    id: "expense-ratio", slug: "expense-ratio-calculator", name: "Expense Ratio Calculator", shortDescription: "Cost impact of fund expense ratios",
    description: "Calculate the true long-term cost of fund expense ratios and how they impact your investment returns.",
    category: "personal-finance", icon: "📉", color: "from-red-500 to-rose-500", timeToComplete: "2 min",
    tags: ["expense ratio", "fund fees", "investment costs"],
    related: ["etf-calculator", "mutual-fund-calculator", "investment-return-calculator"],
    seoTitle: "Expense Ratio Calculator – True Cost of Investment Fees",
    seoDescription: "Calculate how expense ratios erode investment returns over time. Find the true cost of fund fees.",
    keywords: ["expense ratio calculator", "fund expense calculator", "investment fee calculator"],
  },
  {
    id: "debt-to-income", slug: "debt-to-income-calculator", name: "Debt-to-Income Ratio Calculator", shortDescription: "Check your DTI ratio for loan approval",
    description: "Calculate your debt-to-income (DTI) ratio and see if you qualify for mortgage and other loans.",
    category: "personal-finance", icon: "⚖️", color: "from-orange-500 to-red-500", timeToComplete: "2 min",
    tags: ["debt to income ratio", "DTI", "loan qualification"],
    related: ["mortgage-affordability-calculator", "net-worth-calculator", "budget-planner"],
    seoTitle: "Debt-to-Income Ratio Calculator – DTI for Loan Approval",
    seoDescription: "Calculate your debt-to-income (DTI) ratio. See if you qualify for a mortgage or other loans.",
    keywords: ["debt to income calculator", "DTI calculator", "DTI ratio calculator"],
  },
  {
    id: "salary", slug: "salary-calculator", name: "Salary Calculator", shortDescription: "Convert salary to hourly, daily, weekly",
    description: "Convert any salary to all payment frequencies: hourly, daily, weekly, biweekly, monthly, and annual.",
    category: "personal-finance", icon: "💼", color: "from-blue-500 to-indigo-500", timeToComplete: "1 min",
    tags: ["salary", "income", "pay frequency", "hourly wage"],
    related: ["hourly-wage-calculator", "take-home-pay-calculator", "income-tax-calculator"],
    seoTitle: "Salary Calculator – Convert Salary to Hourly, Monthly & Annual",
    seoDescription: "Convert salary between hourly, daily, weekly, biweekly, monthly, and annual pay periods instantly.",
    keywords: ["salary calculator", "pay calculator", "income calculator"],
  },
  {
    id: "hourly-wage", slug: "hourly-wage-calculator", name: "Hourly Wage Calculator", shortDescription: "Convert hourly rate to annual salary",
    description: "Convert hourly wages to annual salary and see take-home pay after taxes and deductions.",
    category: "personal-finance", icon: "⏱️", color: "from-teal-500 to-cyan-500", timeToComplete: "1 min",
    tags: ["hourly wage", "hourly rate", "annual salary"],
    related: ["salary-calculator", "take-home-pay-calculator", "income-tax-calculator"],
    seoTitle: "Hourly Wage Calculator – Convert Hourly Rate to Annual Salary",
    seoDescription: "Convert hourly wage to annual salary, monthly, weekly pay. Calculate take-home pay after taxes.",
    keywords: ["hourly wage calculator", "hourly to salary calculator", "wage calculator"],
  },
  {
    id: "take-home-pay", slug: "take-home-pay-calculator", name: "Take Home Pay Calculator", shortDescription: "Net pay after all deductions",
    description: "Calculate your take-home pay after federal tax, state tax, Social Security, Medicare, and other deductions.",
    category: "personal-finance", icon: "💵", color: "from-green-500 to-teal-500", popular: true, timeToComplete: "3 min",
    tags: ["take home pay", "net pay", "paycheck calculator"],
    related: ["salary-calculator", "income-tax-calculator", "self-employment-tax-calculator"],
    seoTitle: "Take Home Pay Calculator – Net Pay After Taxes & Deductions",
    seoDescription: "Calculate your take-home pay after all deductions including federal tax, state tax, and FICA.",
    keywords: ["take home pay calculator", "net pay calculator", "paycheck calculator"],
  },
  {
    id: "inflation", slug: "inflation-calculator", name: "Inflation Calculator", shortDescription: "Purchasing power over time",
    description: "Calculate purchasing power loss due to inflation and find the future cost of goods and services.",
    category: "personal-finance", icon: "📊", color: "from-red-500 to-orange-500", timeToComplete: "2 min",
    tags: ["inflation", "purchasing power", "CPI", "real value"],
    related: ["inflation-adjusted-return-calculator", "time-value-calculator", "compound-interest-calculator"],
    seoTitle: "Inflation Calculator – Purchasing Power & CPI Calculator",
    seoDescription: "Calculate the impact of inflation on purchasing power. Find historical and projected value of money over time.",
    keywords: ["inflation calculator", "purchasing power calculator", "CPI calculator"],
  },
  {
    id: "credit-utilization", slug: "credit-utilization-calculator", name: "Credit Utilization Calculator", shortDescription: "Optimize your credit score",
    description: "Calculate your credit utilization ratio and get recommendations to improve your credit score.",
    category: "personal-finance", icon: "📊", color: "from-violet-500 to-purple-500", timeToComplete: "2 min",
    tags: ["credit utilization", "credit score", "credit ratio"],
    related: ["debt-to-income-calculator", "credit-card-payoff-calculator", "net-worth-calculator"],
    seoTitle: "Credit Utilization Calculator – Improve Your Credit Score",
    seoDescription: "Calculate credit utilization ratio across all cards. Get recommendations to optimize your credit score.",
    keywords: ["credit utilization calculator", "credit ratio calculator", "credit score calculator"],
  },
  {
    id: "financial-health", slug: "financial-health-score-calculator", name: "Financial Health Score Calculator", shortDescription: "Get your overall financial wellness score",
    description: "Get a comprehensive financial health score analyzing savings rate, debt, insurance, investments, and emergency fund.",
    category: "personal-finance", icon: "❤️", color: "from-pink-500 to-rose-500", featured: true, timeToComplete: "5 min",
    tags: ["financial health", "financial wellness", "financial score"],
    related: ["net-worth-calculator", "budget-planner", "financial-independence-calculator"],
    seoTitle: "Financial Health Score Calculator – Rate Your Financial Wellness",
    seoDescription: "Get your comprehensive financial health score analyzing savings, debt, insurance, investments, and emergency fund.",
    keywords: ["financial health score", "financial wellness calculator", "money health check"],
  },

  // CURRENCY
  {
    id: "currency-exchange", slug: "currency-exchange-calculator", name: "Currency Exchange Calculator", shortDescription: "Live currency conversion calculator",
    description: "Convert between any two currencies with live exchange rates and historical rate comparison.",
    category: "currency", icon: "💱", color: "from-sky-500 to-blue-500", timeToComplete: "1 min",
    tags: ["currency exchange", "forex", "exchange rate", "currency converter"],
    related: ["vat-calculator", "inflation-calculator", "interest-rate-calculator"],
    seoTitle: "Currency Exchange Calculator – Live Currency Converter",
    seoDescription: "Convert any currency with live exchange rates. Calculate foreign exchange amounts instantly.",
    keywords: ["currency exchange calculator", "currency converter", "forex calculator"],
  },
  {
    id: "interest-rate", slug: "interest-rate-calculator", name: "Interest Rate Calculator", shortDescription: "Find the interest rate on any loan",
    description: "Calculate the interest rate given principal, payment, and term for any financial instrument.",
    category: "currency", icon: "🔢", color: "from-blue-600 to-indigo-500", timeToComplete: "2 min",
    tags: ["interest rate", "APR", "rate calculation"],
    related: ["apr-apy-calculator", "emi-calculator", "compound-interest-calculator"],
    seoTitle: "Interest Rate Calculator – Find the Rate on Any Loan",
    seoDescription: "Calculate the implied interest rate given loan amount, payment, and term. Find APR on any financial product.",
    keywords: ["interest rate calculator", "loan interest rate calculator", "APR calculator"],
  },
  {
    id: "apr-apy", slug: "apr-vs-apy-calculator", name: "APR vs APY Calculator", shortDescription: "Convert between APR and APY",
    description: "Convert between APR and APY, understand the difference, and find the true effective interest rate.",
    category: "currency", icon: "🔄", color: "from-teal-500 to-green-500", timeToComplete: "2 min",
    tags: ["APR", "APY", "effective interest rate", "compounding"],
    related: ["interest-rate-calculator", "compound-interest-calculator", "effective-interest-rate-calculator"],
    seoTitle: "APR vs APY Calculator – Convert Between APR and APY",
    seoDescription: "Convert between APR and APY. Understand effective interest rates and find the true cost of borrowing.",
    keywords: ["APR vs APY calculator", "APR to APY converter", "effective rate calculator"],
  },
  {
    id: "simple-interest", slug: "simple-interest-calculator", name: "Simple Interest Calculator", shortDescription: "Calculate basic interest on loans",
    description: "Calculate simple interest, total amount payable, and compare with compound interest.",
    category: "currency", icon: "📐", color: "from-green-500 to-emerald-500", timeToComplete: "1 min",
    tags: ["simple interest", "SI", "interest calculation"],
    related: ["compound-interest-calculator", "emi-calculator", "apr-apy-calculator"],
    seoTitle: "Simple Interest Calculator – SI Formula & Calculator",
    seoDescription: "Calculate simple interest on loans and deposits. Compare simple vs compound interest growth.",
    keywords: ["simple interest calculator", "SI calculator", "interest formula calculator"],
  },
  {
    id: "effective-interest-rate", slug: "effective-interest-rate-calculator", name: "Effective Interest Rate Calculator", shortDescription: "True annual borrowing cost",
    description: "Calculate the effective interest rate (EIR) and effective annual rate (EAR) for accurate loan cost comparison.",
    category: "currency", icon: "🎯", color: "from-violet-500 to-indigo-500", timeToComplete: "2 min",
    tags: ["effective interest rate", "EIR", "EAR", "true cost"],
    related: ["apr-apy-calculator", "interest-rate-calculator", "compound-interest-calculator"],
    seoTitle: "Effective Interest Rate Calculator – True Annual Rate",
    seoDescription: "Calculate effective interest rate (EIR) and effective annual rate (EAR) for accurate borrowing cost comparison.",
    keywords: ["effective interest rate calculator", "EIR calculator", "EAR calculator"],
  },

  // INSURANCE
  {
    id: "life-insurance", slug: "life-insurance-calculator", name: "Life Insurance Needs Calculator", shortDescription: "How much life insurance do you need?",
    description: "Calculate the right amount of life insurance based on income, debts, dependents, and future obligations.",
    category: "insurance", icon: "🛡️", color: "from-emerald-500 to-green-500", timeToComplete: "4 min",
    tags: ["life insurance", "coverage amount", "death benefit"],
    related: ["disability-insurance-calculator", "net-worth-calculator", "budget-planner"],
    seoTitle: "Life Insurance Calculator – How Much Coverage Do You Need?",
    seoDescription: "Calculate the right life insurance coverage amount based on income replacement, debts, and family needs.",
    keywords: ["life insurance calculator", "life insurance needs calculator", "how much life insurance"],
  },
  {
    id: "disability-insurance", slug: "disability-insurance-calculator", name: "Disability Insurance Calculator", shortDescription: "Protect your income",
    description: "Calculate how much disability insurance coverage you need to protect your income if you can't work.",
    category: "insurance", icon: "🏥", color: "from-blue-500 to-cyan-500", timeToComplete: "3 min",
    tags: ["disability insurance", "income protection", "disability coverage"],
    related: ["life-insurance-calculator", "salary-calculator", "emergency-fund-calculator"],
    seoTitle: "Disability Insurance Calculator – Income Protection Coverage",
    seoDescription: "Calculate disability insurance coverage needed to protect your income in case of illness or injury.",
    keywords: ["disability insurance calculator", "income protection calculator", "disability coverage calculator"],
  },
  {
    id: "home-insurance", slug: "home-insurance-calculator", name: "Home Insurance Cost Calculator", shortDescription: "Estimate home insurance premiums",
    description: "Estimate home insurance premiums based on home value, location, coverage level, and risk factors.",
    category: "insurance", icon: "🏠", color: "from-amber-500 to-orange-500", timeToComplete: "3 min",
    tags: ["home insurance", "homeowner insurance", "property insurance"],
    related: ["property-tax-calculator", "mortgage-calculator", "life-insurance-calculator"],
    seoTitle: "Home Insurance Cost Calculator – Estimate Homeowners Insurance",
    seoDescription: "Estimate home insurance premiums based on home value, location, coverage, and deductible amount.",
    keywords: ["home insurance calculator", "homeowners insurance calculator", "property insurance calculator"],
  },
  {
    id: "auto-insurance", slug: "auto-insurance-calculator", name: "Auto Insurance Cost Calculator", shortDescription: "Estimate car insurance premiums",
    description: "Estimate auto insurance premiums based on vehicle, driver profile, coverage level, and deductibles.",
    category: "insurance", icon: "🚗", color: "from-slate-500 to-blue-500", timeToComplete: "3 min",
    tags: ["auto insurance", "car insurance", "vehicle insurance"],
    related: ["car-loan-calculator", "life-insurance-calculator", "home-insurance-calculator"],
    seoTitle: "Auto Insurance Cost Calculator – Car Insurance Estimate",
    seoDescription: "Estimate auto insurance premiums based on your vehicle, driving history, coverage needs, and location.",
    keywords: ["auto insurance calculator", "car insurance calculator", "vehicle insurance calculator"],
  },
  {
    id: "health-insurance", slug: "health-insurance-affordability-calculator", name: "Health Insurance Affordability Calculator", shortDescription: "Find affordable health coverage",
    description: "Calculate health insurance affordability, ACA subsidy eligibility, and compare plan costs with expected usage.",
    category: "insurance", icon: "❤️", color: "from-rose-500 to-red-500", timeToComplete: "4 min",
    tags: ["health insurance", "ACA subsidy", "health coverage", "premium"],
    related: ["income-tax-calculator", "take-home-pay-calculator", "budget-planner"],
    seoTitle: "Health Insurance Affordability Calculator – ACA Subsidy Estimator",
    seoDescription: "Calculate health insurance affordability and ACA subsidy eligibility. Compare plan costs based on your income.",
    keywords: ["health insurance calculator", "ACA calculator", "health insurance affordability calculator"],
  },
];

export function getCalculatorBySlug(slug: string): CalculatorMeta | undefined {
  return CALCULATORS.find(c => c.slug === slug);
}

export function getCalculatorsByCategory(category: CalculatorCategory): CalculatorMeta[] {
  return CALCULATORS.filter(c => c.category === category);
}

export function getFeaturedCalculators(): CalculatorMeta[] {
  return CALCULATORS.filter(c => c.featured);
}

export function getPopularCalculators(): CalculatorMeta[] {
  return CALCULATORS.filter(c => c.popular);
}

export function getRelatedCalculators(slugs: string[]): CalculatorMeta[] {
  return slugs.map(slug => getCalculatorBySlug(slug)).filter(Boolean) as CalculatorMeta[];
}

export function getAllCategories(): CalculatorCategory[] {
  return Object.keys(CATEGORY_META) as CalculatorCategory[];
}
