import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer – FinCalcPro",
  description: "Important disclaimer about FinCalcPro financial calculators. Results are estimates for informational purposes only.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen">
      <div className="border-b border-[var(--border)] bg-[var(--muted)] py-12">
        <div className="mx-auto max-w-3xl px-4 lg:px-8">
          <h1 className="text-3xl font-bold text-[var(--foreground)] mb-2">Disclaimer</h1>
          <p className="text-sm text-[var(--muted-foreground)]">Last updated: June 29, 2026</p>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-4 py-12 lg:px-8">
        <div className="space-y-8 text-[var(--muted-foreground)] leading-relaxed">

          {/* Main disclaimer box */}
          <div className="rounded-2xl border border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-900/20 p-6">
            <h2 className="text-base font-bold text-amber-900 dark:text-amber-200 mb-2">⚠️ Not Financial Advice</h2>
            <p className="text-amber-800 dark:text-amber-300 text-sm leading-relaxed">
              All content, tools, and calculators on FinCalcPro are for <strong>informational and educational purposes only</strong>. Nothing on this website constitutes financial, investment, tax, legal, or accounting advice. Always consult a qualified professional before making financial decisions.
            </p>
          </div>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">1. General Disclaimer</h2>
            <p>FinCalcPro provides financial calculators as educational tools to help users understand financial concepts and estimate potential outcomes. The results generated by our calculators are mathematical estimates based on the inputs provided and should not be interpreted as guarantees, projections, or professional financial guidance.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">2. Accuracy of Results</h2>
            <p>While we strive for accuracy in our formulas and calculations, actual financial results will vary based on numerous factors including but not limited to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Changes in interest rates and market conditions</li>
              <li>Inflation and purchasing power changes</li>
              <li>Tax law changes at federal, state, or local levels</li>
              <li>Individual circumstances not captured by calculator inputs</li>
              <li>Fees, charges, and transaction costs not included in calculations</li>
              <li>Regulatory changes affecting financial products</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">3. Investment Disclaimer</h2>
            <p>Investment calculators on FinCalcPro use hypothetical rates of return for illustration purposes only. Past investment performance does not guarantee future results. The value of investments can go down as well as up, and you may receive back less than you invest.</p>
            <p className="mt-3">We are not registered investment advisors and do not recommend specific investment products, securities, or strategies.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">4. Tax Disclaimer</h2>
            <p>Tax calculators on FinCalcPro provide estimates based on published tax rates and brackets. They do not account for all possible deductions, credits, alternative minimum tax, state-specific rules, or individual tax situations. Consult a qualified tax professional or the relevant tax authority for accurate tax advice.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">5. Mortgage &amp; Loan Disclaimer</h2>
            <p>Mortgage and loan calculator results are illustrative estimates only. Actual loan terms, interest rates, and monthly payments will be determined by lenders based on creditworthiness, loan-to-value ratios, and other factors. Consult directly with a licensed lender for actual loan terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">6. Third-Party Information</h2>
            <p>Links to third-party websites are provided for convenience. FinCalcPro does not endorse, control, or take responsibility for content on third-party sites.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">7. Seek Professional Advice</h2>
            <p>Before making any significant financial decision — including investments, taking on debt, retirement planning, or tax filing — we strongly recommend consulting with:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>A Certified Financial Planner (CFP) for investment and retirement planning</li>
              <li>A Chartered Accountant (CA) or CPA for tax matters</li>
              <li>A licensed mortgage broker or lender for home financing</li>
              <li>A qualified solicitor or attorney for legal matters</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-[var(--foreground)] mb-3">8. Contact</h2>
            <p>For questions about this disclaimer, contact <a href="mailto:legal@fincalcpro.com" className="text-[var(--primary)] hover:underline">legal@fincalcpro.com</a>.</p>
          </section>

        </div>
      </div>
    </div>
  );
}
